sonar.projectKey=MiguelZod24_AutomationExercise_Project
sonar.organization=miguelzod24
sonar.projectName=AutomationExercise_Project

sonar.sources=pages
sonar.tests=tests
sonar.python.version=3.11

sonar.exclusions=**/__pycache__/**,reports/**,scripts/**,.github/**
sonar.test.exclusions=tests/**

sonar.python.xunit.reportPaths=reports/results.xml
